services:
  frontend:
    ports: 
      - "80:80"
    build: ./frontend
    networks:
      - main_network
  backend:
    ports: 
      - "8000:8000"
    build: ./backend
    networks:
     - main_network
networks:
  main_network:
    driver: bridge
